[package]
name = "ptyr"
version = "0.1.0"
authors = ["Max Fierke <max@maxfierke.com>"]

[dependencies]
errno = "*"
libc = "*"
nix = "0.11.0"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = "0.4.2"

[lib]
crate-type = ["staticlib"]
